AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - "config/**/*"
    - 'db/**/*'
    - "lib/**/*"
    # - 'spec/**/*'
    - 'vendor/**/*'
    - 'app/helpers/page_helper.rb'

# メソッドの代入、メソッド呼び出し、条件分岐のサイズが設定された最大値を超えていないことを確認します。
Metrics/AbcSize:
  Max: 23.28

# メソッドの長さが最大値を超えるかどうか
Metrics/MethodLength:
  CountComments: false
  Max: 14

# has_, is_, have_ など、特定の文字列で始まるメソッド名をチェック
Naming/PredicateName:
    Enabled: false

# hoge = if fuga
Style/ConditionalAssignment:
  Enabled: false

# ドキュメントの無いpublic classを確認
Style/Documentation:
  Enabled: false

# 文字列がfreezeされていないと警告が出る
Style/FrozenStringLiteralComment:
  Enabled: false

# 多重代入 後で消すかも
Style/ParallelAssignment:
  Enabled: false

# 翻訳 後で消すかも
Rails/I18nLocaleTexts:
  Enabled: false

require:
    - rubocop-rails
    - rubocop-rspec
