google:
  place_type: {
      'パン屋': 'bakery',
      '銀行': 'bank',
      '本屋': 'book_store',
      'カフェ': 'cafe',
      '市役所': 'city_hall',
      '服屋': 'clothing_store',
      'コンビニエンスストア': 'convenience_store',
      'デパート': 'department_store',
      'ドラッグストア': 'drugstore',
      '花屋': 'florist',
      '家具店': 'furniture_store',
      'ランドリー': 'home_goods_store',
      '図書館': 'library',
      'レストラン': 'restaurant',
      '学校': 'school',
      '靴屋': 'shoe_store',
      'ショッピングモール': 'shopping_mall',
      'スパ': 'spa',
      '店舗': 'store',
      'スーパーマーケット': 'supermarket',
      '観光スポット': 'tourist_attraction',
  }
course_type: [
  'one_way',
  'round_trip',
]
turbo_frame_for_check_session: [
  'record-field',
  'start-field',
]
